Imports System.Data.Entity
Public Class frmProReports
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Instantiate a new DBContext
        Dim dbContext As CsmdBioDatabase.CsmdBioAttendenceEntities = New CsmdBioDatabase.CsmdBioAttendenceEntities()
        ' Call the Load method to get the data for the given DbSet from the database.
        dbContext.Emp_Att_Payment.Load()
        ' This line of code is generated by Data Source Configuration Wizard
        BindingSource1.DataSource = dbContext.Emp_Att_Payment.Local.ToBindingList()
    End Sub
End Class