'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Attendence_Status
    Public Property Attendence_Status_ID As Integer
    Public Property Attendence_Status_Type As String
    Public Property Attendence_Status_Dep As String
    Public Property Attendence_Status_Finger As String

    Public Overridable Property Emp_Bio_Device_Users As ICollection(Of Emp_Bio_Device_Users) = New HashSet(Of Emp_Bio_Device_Users)

End Class
