'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emp_Att_Set
    Public Property Emp_Att_Set_ID As Integer
    Public Property User_ID As Nullable(Of Integer)
    Public Property Emp_Att_Set_Open_Time As String
    Public Property Emp_Att_Set_Close_Time As String
    Public Property Emp_Att_Set_Fri_Status As Nullable(Of Boolean)
    Public Property Emp_Att_Set_DutyFriOn As String
    Public Property Emp_Att_Set_DutyFriOff As String
    Public Property Emp_Att_Set_FridayOff As String
    Public Property Emp_Att_Set_Late_Arrival_Status As Nullable(Of Boolean)
    Public Property Emp_Att_Set_Late_Arrival_Time As Nullable(Of Double)
    Public Property Emp_Att_Set_Early_Status As Nullable(Of Boolean)
    Public Property Emp_Att_Set_Early_Time As Nullable(Of Double)
    Public Property Emp_Att_Set_Duty_OverTime_Status As Nullable(Of Boolean)
    Public Property Emp_Att_Set_Date As Nullable(Of Date)
    Public Property Emp_Att_Set_Duty_OverTime_Time As Nullable(Of Double)
    Public Property Emp_Att_Set_Prayer_Late_Status As Nullable(Of Boolean)
    Public Property Emp_Att_Set_Prayer_Late_Time As Nullable(Of Double)
    Public Property Emp_Att_Set_Short_Leave_Status As Nullable(Of Boolean)
    Public Property Emp_Att_Set_Short_Leave_Time As Nullable(Of Double)
    Public Property Emp_Att_Set_Lunch_Status As Nullable(Of Boolean)
    Public Property Emp_Att_Set_Lunch_Time As Nullable(Of Double)
    Public Property Emp_Att_Set_Lunch_OverTime_Status As Nullable(Of Boolean)
    Public Property Emp_Att_Set_Private_Late_Status As Nullable(Of Boolean)
    Public Property Emp_Att_Set_Private_Time As Nullable(Of Double)

    Public Overridable Property Plaza_User As Plaza_User

End Class
