'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emp_Cash_Register
    Public Property Emp_Cash_Register_ID As Integer
    Public Property Emp_Cash_Register_Date As Nullable(Of Date)
    Public Property Emp_Cash_Register_Description As String
    Public Property Emp_Cash_Register_Amt As Nullable(Of Decimal)

End Class
