Imports System.Data.Entity
Imports CsmdBioDatabase

Public Class frmEmpCashRegister
    Dim db As CsmdBioDatabase.CsmdBioAttendenceEntities = New CsmdBioDatabase.CsmdBioAttendenceEntities
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Instantiate a new DBContext

        ' Call the Load method to get the data for the given DbSet from the database.
        db.Emp_Cash_Register.Load()
        ' This line of code is generated by Data Source Configuration Wizard
        BindingSource1.DataSource = db.Emp_Cash_Register.Local.ToBindingList()
    End Sub

    Private Sub GridView1_RowUpdated(sender As Object, e As DevExpress.XtraGrid.Views.Base.RowObjectEventArgs) Handles GridView1.RowUpdated
        db.SaveChanges()
    End Sub

    Private Sub BarButtonItem1_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem1.ItemClick
        GridView1.OptionsBehavior.Editable = True
    End Sub

    Private Sub BarButtonItem2_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem2.ItemClick
        GridView1.OptionsBehavior.Editable = False
    End Sub

    Private Sub frmEmpCashRegister_FormClosing(sender As Object, e As FormClosingEventArgs) Handles Me.FormClosing
        Dim frm As frmEmployeesCalculations = frmMain.TabX1.ActiveDocument.Form
        frm.Load_Payment_Month_Single(CsmdVarible.intEmpID, CDate(frm.Issue_Date.EditValue))
    End Sub
End Class