'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Auto_Number
    Public Property Auto_ID As Integer
    Public Property Auto_Emp_Num As Nullable(Of Integer)
    Public Property Auto_Invoice As Nullable(Of Integer)
    Public Property Auto_Receipt As Nullable(Of Integer)
    Public Property Auto_Bill_Invoice As Nullable(Of Integer)
    Public Property Auto_Bill_Receipt As Nullable(Of Integer)
    Public Property Auto_Cus_No As Nullable(Of Integer)
    Public Property Payroll_Receipt As Nullable(Of Integer)
    Public Property Sch_Shop_Invoice_Number As Nullable(Of Integer)
    Public Property Auto_Floor_Detail_Sr As Nullable(Of Integer)
    Public Property Auto_Veh_Fuel_Detail_Invoice As Nullable(Of Integer)
    Public Property Auto_Veh_Maintinance_Invoice As Nullable(Of Integer)

End Class
