'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Chart_Of_Accounts
    Public Property Chart_Of_Accounts_ID As Integer
    Public Property Chart_Of_Accounts_Type_ID As Nullable(Of Integer)
    Public Property Chart_Of_Accounts_Code As String
    Public Property Chart_Of_Accounts_Description As String
    Public Property Chart_Of_Accounts_Beginning_Balances As Nullable(Of Double)
    Public Property Chart_Of_Accounts_Status As Nullable(Of Boolean)

    Public Overridable Property Chart_Of_Accounts_Type As Chart_Of_Accounts_Type
    Public Overridable Property Chart_Of_Accounts_Detail As ICollection(Of Chart_Of_Accounts_Detail) = New HashSet(Of Chart_Of_Accounts_Detail)
    Public Overridable Property Emp_Pay_Detail As ICollection(Of Emp_Pay_Detail) = New HashSet(Of Emp_Pay_Detail)
    Public Overridable Property Emp_Pay_Method_Default As ICollection(Of Emp_Pay_Method_Default) = New HashSet(Of Emp_Pay_Method_Default)
    Public Overridable Property Pay_Roll_Cash_Account As ICollection(Of Pay_Roll_Cash_Account) = New HashSet(Of Pay_Roll_Cash_Account)
    Public Overridable Property Pay_Roll As ICollection(Of Pay_Roll) = New HashSet(Of Pay_Roll)
    Public Overridable Property Pay_Roll_Detail As ICollection(Of Pay_Roll_Detail) = New HashSet(Of Pay_Roll_Detail)
    Public Overridable Property RB_Pay_Detail As ICollection(Of RB_Pay_Detail) = New HashSet(Of RB_Pay_Detail)
    Public Overridable Property RB_Pay_Detail1 As ICollection(Of RB_Pay_Detail) = New HashSet(Of RB_Pay_Detail)
    Public Overridable Property RB_Pay_Detail2 As ICollection(Of RB_Pay_Detail) = New HashSet(Of RB_Pay_Detail)
    Public Overridable Property RB_Pay_Detail3 As ICollection(Of RB_Pay_Detail) = New HashSet(Of RB_Pay_Detail)
    Public Overridable Property RB_Pay_Detail4 As ICollection(Of RB_Pay_Detail) = New HashSet(Of RB_Pay_Detail)
    Public Overridable Property RB_Pay_Detail5 As ICollection(Of RB_Pay_Detail) = New HashSet(Of RB_Pay_Detail)
    Public Overridable Property RB_Pay_Detail_Default_Accounts As ICollection(Of RB_Pay_Detail_Default_Accounts) = New HashSet(Of RB_Pay_Detail_Default_Accounts)
    Public Overridable Property Rent_Cash_Account As ICollection(Of Rent_Cash_Account) = New HashSet(Of Rent_Cash_Account)
    Public Overridable Property Sch_Accounts_Default As ICollection(Of Sch_Accounts_Default) = New HashSet(Of Sch_Accounts_Default)
    Public Overridable Property Sch_Accounts_Default1 As ICollection(Of Sch_Accounts_Default) = New HashSet(Of Sch_Accounts_Default)
    Public Overridable Property Sch_Cash_Accounts As ICollection(Of Sch_Cash_Accounts) = New HashSet(Of Sch_Cash_Accounts)

End Class
