'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer_Bridge
    Public Property Cus_Detail_ID As Integer
    Public Property Cus_ID As Nullable(Of Integer)
    Public Property Shop_ID As Nullable(Of Integer)
    Public Property Cus_Detail_Shop_Rate As Nullable(Of Decimal)
    Public Property Cus_Detail_Shop_Meter_No As String
    Public Property Cus_Detail_Shop_Meter_Last_Reading As Nullable(Of Double)
    Public Property Cus_Detail_Shop_Gas_Meter_No As String
    Public Property Cus_Detail_Shop_Gas_Meter_Last_Reading As Nullable(Of Double)
    Public Property Unit_Type_ID As Nullable(Of Integer)
    Public Property Cus_Detail_Date_IN As Nullable(Of Date)
    Public Property Cus_Detail_Date_Out As Nullable(Of Date)
    Public Property Cus_Detail_Status As Nullable(Of Boolean)
    Public Property Cus_Detail_Rent_Status As Nullable(Of Boolean)
    Public Property User_ID As Nullable(Of Integer)

    Public Overridable Property Customer As Customer
    Public Overridable Property Shop As Shop
    Public Overridable Property Unit_Type As Unit_Type
    Public Overridable Property RB_Pay As ICollection(Of RB_Pay) = New HashSet(Of RB_Pay)

End Class
