'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Driver_Payroll
    Public Property Driver_Payroll_ID As Integer
    Public Property Driver_ID As Nullable(Of Integer)
    Public Property Driver_Pay_Type_ID As Nullable(Of Integer)
    Public Property Driver_Payroll_Amount As Nullable(Of Decimal)
    Public Property Driver_Payroll_Date As Nullable(Of Date)

    Public Overridable Property Driver_Pay_Type As Driver_Pay_Type
    Public Overridable Property Driver As Driver

End Class
