'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Driver
    Public Property Driver_ID As Integer
    Public Property Driver_Code As String
    Public Property Driver_Name As String
    Public Property Driver_Father As String
    Public Property Driver_NIC As String
    Public Property Driver_Phone As String
    Public Property Driver_Address As String
    Public Property Driver_Salary As Nullable(Of Decimal)

    Public Overridable Property Driver_Payroll As ICollection(Of Driver_Payroll) = New HashSet(Of Driver_Payroll)
    Public Overridable Property Emb_Calls As ICollection(Of Emb_Calls) = New HashSet(Of Emb_Calls)

End Class
