'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Driver_Pay_Type
    Public Property Driver_Pay_Type_ID As Integer
    Public Property Driver_Pay_Type_Name As String

    Public Overridable Property Driver_Payroll As ICollection(Of Driver_Payroll) = New HashSet(Of Driver_Payroll)

End Class
