'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emb_Calls
    Public Property Emb_Calls_ID As Integer
    Public Property Emergency_ID As Nullable(Of Integer)
    Public Property Hospital_ID As Nullable(Of Integer)
    Public Property Patient_ID As Nullable(Of Integer)
    Public Property Vehicle_ID As Nullable(Of Integer)
    Public Property Driver_ID As Nullable(Of Integer)
    Public Property Emb_Calls_Call_Date As Nullable(Of Date)
    Public Property Emb_Calls_Deliver_Date As Nullable(Of Date)
    Public Property Emb_Calls_Start_MR As Nullable(Of Double)
    Public Property Emb_Calls_End_MR As Nullable(Of Double)
    Public Property Emb_Calls_Total_KM As Nullable(Of Double)
    Public Property Emb_Calls_Rate_Per_KM As Nullable(Of Double)
    Public Property Emb_Calls_Total_Amount As Nullable(Of Decimal)
    Public Property Emb_Calls_Paid_Amount As Nullable(Of Decimal)
    Public Property Emb_Calls_Discount As Nullable(Of Decimal)
    Public Property Emb_Calls_Due As Nullable(Of Decimal)
    Public Property Emb_Calls_Status As Nullable(Of Boolean)

    Public Overridable Property Driver As Driver
    Public Overridable Property Emergency As Emergency
    Public Overridable Property Hospital As Hospital
    Public Overridable Property Patient As Patient
    Public Overridable Property Vehicle As Vehicle

End Class
