'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emergency
    Public Property Emergency_ID As Integer
    Public Property Emergency_Name As String

    Public Overridable Property Emb_Calls As ICollection(Of Emb_Calls) = New HashSet(Of Emb_Calls)

End Class
