'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emp_Custom_Fields_Default
    Public Property Emp_Custom_Fields_Default_ID As Integer
    Public Property Emp_Custom_Fields_Default_Caption As String
    Public Property Emp_Custom_Fields_Default_Enable As Nullable(Of Boolean)

    Public Overridable Property Emp_Custom_Fields As ICollection(Of Emp_Custom_Fields) = New HashSet(Of Emp_Custom_Fields)

End Class
