'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emp_Att_Set
    Public Property Emp_Att_Set_ID As Integer
    Public Property Emp_Att_Set_DutyFriOn As String
    Public Property Emp_Att_Set_DutyFriOff As String
    Public Property Emp_Att_Set_FridayOff As String
    Public Property Emp_Att_Set_1 As String
    Public Property Emp_Att_Set_2 As String
    Public Property Emp_Att_Set_3 As String
    Public Property Emp_Att_Set_4 As String
    Public Property Emp_Att_Set_5 As String
    Public Property Emp_Att_Set_Date As Nullable(Of Date)
    Public Property Emp_Att_Set_Fri_Status As Nullable(Of Boolean)

End Class
