'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emp_Attendence
    Public Property Emp_Attendence_ID As Integer
    Public Property Emp_ID As Nullable(Of Integer)
    Public Property Emp_Fingers_ID As Nullable(Of Integer)
    Public Property Fingers_ID As Nullable(Of Integer)
    Public Property Emp_Attendence_Att_Status_ID As Nullable(Of Integer)
    Public Property Emp_Attendence_Date As Nullable(Of Date)
    Public Property Emp_Attendence_Time As String
    Public Property User_ID As Nullable(Of Integer)

    Public Overridable Property Att_Status As Att_Status
    Public Overridable Property Emp_Fingers As Emp_Fingers
    Public Overridable Property Employee As Employee
    Public Overridable Property Finger As Finger
    Public Overridable Property Plaza_User As Plaza_User

End Class
