'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emp_Pay_Method
    Public Property Emp_Pay_Method_ID As Integer
    Public Property Emp_Pay_Method_Type As String

    Public Overridable Property Emp_Pay As ICollection(Of Emp_Pay) = New HashSet(Of Emp_Pay)
    Public Overridable Property Emp_Pay_Method_Default As ICollection(Of Emp_Pay_Method_Default) = New HashSet(Of Emp_Pay_Method_Default)

End Class
