'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emp_Salary_Creater
    Public Property Emp_Salary_Creater_ID As Integer
    Public Property Emp_ID As Nullable(Of Integer)
    Public Property Emp_Salary_Creater_IssueDate As Nullable(Of Date)
    Public Property Emp_Salary_Creater_From As Nullable(Of Date)
    Public Property Emp_Salary_Creater_To As Nullable(Of Date)
    Public Property Emp_Salary_Creater_DutyOn As String
    Public Property Emp_Salary_Creater_DutyOff As String
    Public Property Emp_Salary_Creater_DutyFriOff As String
    Public Property Emp_Salary_Creater_Total_Hours As String
    Public Property Emp_Salary_Creater_Total_Days As String
    Public Property Emp_Salary_Creater_Total_DayRate As String
    Public Property Emp_Salary_Creater_Total_MinRate As String
    Public Property Emp_Salary_Creater_Total_Salary As String
    Public Property Emp_Salary_Creater_ExtraDays As String
    Public Property Emp_Salary_Creater_Absent_D As String
    Public Property Emp_Salary_Creater_Absent_Amount As String
    Public Property Emp_Salary_Creater_InOutDays As String
    Public Property Emp_Salary_Creater_Late_H As String
    Public Property Emp_Salary_Creater_Late_D As String
    Public Property Emp_Salary_Creater_Late_Amount As String
    Public Property Emp_Salary_Creater_Early_H As String
    Public Property Emp_Salary_Creater_Early_D As String
    Public Property Emp_Salary_Creater_Early_Amount As String
    Public Property Emp_Salary_Creater_OverTime_H As String
    Public Property Emp_Salary_Creater_OverTime_D As String
    Public Property Emp_Salary_Creater_OverTime_Amount As String
    Public Property Emp_Salary_Creater_Private_Late_H As String
    Public Property Emp_Salary_Creater_Private_Late_D As String
    Public Property Emp_Salary_Creater_Private_Late_Amount As String
    Public Property Emp_Salary_Creater_Short_H As String
    Public Property Emp_Salary_Creater_Short_D As String
    Public Property Emp_Salary_Creater_Short_Amount As String
    Public Property Emp_Salary_Creater_Lunch_Late_H As String
    Public Property Emp_Salary_Creater_Lunch_Late_D As String
    Public Property Emp_Salary_Creater_Lunch_Late_Amount As String
    Public Property Emp_Salary_Creater_Lunch_OverTime_H As String
    Public Property Emp_Salary_Creater_Lunch_OverTime_D As String
    Public Property Emp_Salary_Creater_Lunch_OverTime_Amount As String
    Public Property Emp_Salary_Creater_Prayer_Late_H As String
    Public Property Emp_Salary_Creater_Prayer_Late_D As String
    Public Property Emp_Salary_Creater_Prayer_Late_Amount As String
    Public Property Emp_Salary_Creater_Total_Amount As String

    Public Overridable Property Employee As Employee

End Class
