'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emp_Custom_Fields
    Public Property Emp_Custom_ID As Integer
    Public Property Emp_ID As Nullable(Of Integer)
    Public Property Emp_Custom_Fields_Default_ID As Nullable(Of Integer)
    Public Property Emp_Custom_Fields_Default_Text As String

    Public Overridable Property Emp_Custom_Fields_Default As Emp_Custom_Fields_Default
    Public Overridable Property Employee As Employee

End Class
