'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emp_Pay_Method_Default
    Public Property Emp_Pay_Method_Default_ID As Integer
    Public Property Emp_Pay_Method_ID As Nullable(Of Integer)
    Public Property Emp_Pay_Salary_Default_FieldName As String
    Public Property Emp_Pay_Salary_Default_GL_Accounts_ID As Nullable(Of Integer)

    Public Overridable Property Chart_Of_Accounts As Chart_Of_Accounts
    Public Overridable Property Emp_Pay_Detail As ICollection(Of Emp_Pay_Detail) = New HashSet(Of Emp_Pay_Detail)
    Public Overridable Property Emp_Pay_Method As Emp_Pay_Method

End Class
