'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Floor
    Public Property Floor_ID As Integer
    Public Property Plaza_ID As Nullable(Of Integer)
    Public Property Floor_Name As String
    Public Property Floor_Meter_No As String
    Public Property Shop_Meter_Last_Reading As Nullable(Of Double)

    Public Overridable Property Floor_Detail As ICollection(Of Floor_Detail) = New HashSet(Of Floor_Detail)
    Public Overridable Property Plaza As Plaza
    Public Overridable Property Shops As ICollection(Of Shop) = New HashSet(Of Shop)

End Class
