'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Hospital
    Public Property Hospital_ID As Integer
    Public Property Hospital_Type_ID As Nullable(Of Integer)
    Public Property Hospital_Name As String
    Public Property Hospital_Address As String

    Public Overridable Property Emb_Calls As ICollection(Of Emb_Calls) = New HashSet(Of Emb_Calls)
    Public Overridable Property Hospital_Type As Hospital_Type

End Class
