'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CsmdBioAttendenceEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CsmdBioAttendenceEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Accounts() As DbSet(Of Account)
    Public Overridable Property Addresses() As DbSet(Of Address)
    Public Overridable Property Att_Status() As DbSet(Of Att_Status)
    Public Overridable Property Attendence_Status() As DbSet(Of Attendence_Status)
    Public Overridable Property Auto_Number() As DbSet(Of Auto_Number)
    Public Overridable Property Chart_Of_Accounts() As DbSet(Of Chart_Of_Accounts)
    Public Overridable Property Chart_Of_Accounts_Detail() As DbSet(Of Chart_Of_Accounts_Detail)
    Public Overridable Property Chart_Of_Accounts_Type() As DbSet(Of Chart_Of_Accounts_Type)
    Public Overridable Property Customers() As DbSet(Of Customer)
    Public Overridable Property Customer_Bridge() As DbSet(Of Customer_Bridge)
    Public Overridable Property Designations() As DbSet(Of Designation)
    Public Overridable Property Driver_Pay_Type() As DbSet(Of Driver_Pay_Type)
    Public Overridable Property Driver_Payroll() As DbSet(Of Driver_Payroll)
    Public Overridable Property Drivers() As DbSet(Of Driver)
    Public Overridable Property Emb_Calls() As DbSet(Of Emb_Calls)
    Public Overridable Property Emergencies() As DbSet(Of Emergency)
    Public Overridable Property Emp_Att_Set() As DbSet(Of Emp_Att_Set)
    Public Overridable Property Emp_Attendence() As DbSet(Of Emp_Attendence)
    Public Overridable Property Emp_Custom_Fields() As DbSet(Of Emp_Custom_Fields)
    Public Overridable Property Emp_Custom_Fields_Default() As DbSet(Of Emp_Custom_Fields_Default)
    Public Overridable Property Emp_Fingers() As DbSet(Of Emp_Fingers)
    Public Overridable Property Emp_Pay() As DbSet(Of Emp_Pay)
    Public Overridable Property Emp_Pay_Detail() As DbSet(Of Emp_Pay_Detail)
    Public Overridable Property Emp_Pay_Frequency() As DbSet(Of Emp_Pay_Frequency)
    Public Overridable Property Emp_Pay_Method() As DbSet(Of Emp_Pay_Method)
    Public Overridable Property Emp_Pay_Method_Default() As DbSet(Of Emp_Pay_Method_Default)
    Public Overridable Property Emp_Title() As DbSet(Of Emp_Title)
    Public Overridable Property Employees() As DbSet(Of Employee)
    Public Overridable Property Fingers() As DbSet(Of Finger)
    Public Overridable Property Floors() As DbSet(Of Floor)
    Public Overridable Property Floor_Detail() As DbSet(Of Floor_Detail)
    Public Overridable Property Fuel_Pump() As DbSet(Of Fuel_Pump)
    Public Overridable Property Genders() As DbSet(Of Gender)
    Public Overridable Property Hospitals() As DbSet(Of Hospital)
    Public Overridable Property Hospital_Type() As DbSet(Of Hospital_Type)
    Public Overridable Property Nic_Type() As DbSet(Of Nic_Type)
    Public Overridable Property Patients() As DbSet(Of Patient)
    Public Overridable Property Pay_Roll() As DbSet(Of Pay_Roll)
    Public Overridable Property Pay_Roll_Cash_Account() As DbSet(Of Pay_Roll_Cash_Account)
    Public Overridable Property Pay_Roll_Detail() As DbSet(Of Pay_Roll_Detail)
    Public Overridable Property Plazas() As DbSet(Of Plaza)
    Public Overridable Property Plaza_User() As DbSet(Of Plaza_User)
    Public Overridable Property RB_Pay() As DbSet(Of RB_Pay)
    Public Overridable Property RB_Pay_Detail() As DbSet(Of RB_Pay_Detail)
    Public Overridable Property RB_Pay_Detail_Default_Accounts() As DbSet(Of RB_Pay_Detail_Default_Accounts)
    Public Overridable Property RB_Pay_Detail_Payments() As DbSet(Of RB_Pay_Detail_Payments)
    Public Overridable Property RB_Pay_Per() As DbSet(Of RB_Pay_Per)
    Public Overridable Property Rent_Cash_Account() As DbSet(Of Rent_Cash_Account)
    Public Overridable Property Sch_Accounts() As DbSet(Of Sch_Accounts)
    Public Overridable Property Sch_Accounts_Default() As DbSet(Of Sch_Accounts_Default)
    Public Overridable Property Sch_Cash_Accounts() As DbSet(Of Sch_Cash_Accounts)
    Public Overridable Property Shops() As DbSet(Of Shop)
    Public Overridable Property Shop_Type() As DbSet(Of Shop_Type)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property UnGs() As DbSet(Of UnG)
    Public Overridable Property Unit_Type() As DbSet(Of Unit_Type)
    Public Overridable Property User_Type() As DbSet(Of User_Type)
    Public Overridable Property Veh_Expensee_Type() As DbSet(Of Veh_Expensee_Type)
    Public Overridable Property Veh_Fuel_Detail() As DbSet(Of Veh_Fuel_Detail)
    Public Overridable Property Veh_Fuel_Type() As DbSet(Of Veh_Fuel_Type)
    Public Overridable Property Veh_Maintinance() As DbSet(Of Veh_Maintinance)
    Public Overridable Property Veh_Type() As DbSet(Of Veh_Type)
    Public Overridable Property Vehicles() As DbSet(Of Vehicle)
    Public Overridable Property Emp_Salary_Creater() As DbSet(Of Emp_Salary_Creater)
    Public Overridable Property Emp_Att_Payment() As DbSet(Of Emp_Att_Payment)
    Public Overridable Property Emp_Attendence_Device() As DbSet(Of Emp_Attendence_Device)
    Public Overridable Property Emp_Bio_Device_Users() As DbSet(Of Emp_Bio_Device_Users)

End Class
