'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Patient
    Public Property Patient_ID As Integer
    Public Property Patient_Name As String
    Public Property Patient_Father As String
    Public Property Patient_NIC As String
    Public Property Patient_Phone As String
    Public Property Patient_Address As String
    Public Property Patient_Guardian_Name As String
    Public Property Patient_Guardian_Father As String
    Public Property Patient_Guardian_NIC As String
    Public Property Patient_Guardian_Phone As String

    Public Overridable Property Emb_Calls As ICollection(Of Emb_Calls) = New HashSet(Of Emb_Calls)

End Class
