'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pay_Roll_Detail
    Public Property Pay_Roll_Detail_ID As Integer
    Public Property Pay_Roll_ID As Nullable(Of Integer)
    Public Property Chart_Of_Accounts_ID As Nullable(Of Integer)
    Public Property Emp_Pay_Detail_Field_Name As String
    Public Property Pay_Roll_Detail_Debits As Nullable(Of Double)
    Public Property Pay_Roll_Detail_Credits As Nullable(Of Double)
    Public Property Pay_Roll_Detail_Period_History As Nullable(Of Date)
    Public Property Pay_Roll_Detail_Period_Activity As Nullable(Of Double)
    Public Property Pay_Roll_Detail_Running_Balance As Nullable(Of Double)

    Public Overridable Property Chart_Of_Accounts As Chart_Of_Accounts
    Public Overridable Property Pay_Roll As Pay_Roll

End Class
