'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pay_Roll
    Public Property Pay_Roll_ID As Integer
    Public Property Emp_ID As Nullable(Of Integer)
    Public Property Pay_Roll_Check As String
    Public Property Pay_Roll_Date As Nullable(Of Date)
    Public Property Pay_Roll_Pay_Date As Nullable(Of Date)
    Public Property Pay_Roll_Amount As Nullable(Of Decimal)
    Public Property Pay_Roll_Total As Nullable(Of Decimal)
    Public Property Pay_Roll_Paid As Nullable(Of Decimal)
    Public Property Pay_Roll_Balance As Nullable(Of Decimal)
    Public Property Pay_Roll_Status As String
    Public Property Chart_Of_Accounts_ID As Nullable(Of Integer)
    Public Property User_ID As Nullable(Of Integer)

    Public Overridable Property Chart_Of_Accounts As Chart_Of_Accounts
    Public Overridable Property Employee As Employee
    Public Overridable Property Pay_Roll_Detail As ICollection(Of Pay_Roll_Detail) = New HashSet(Of Pay_Roll_Detail)
    Public Overridable Property Plaza_User As Plaza_User

End Class
