'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Plaza_User
    Public Property User_ID As Integer
    Public Property User_Type_ID As Nullable(Of Integer)
    Public Property User_Name As String
    Public Property User_Pass As String
    Public Property User_Status As Nullable(Of Boolean)

    Public Overridable Property Customers As ICollection(Of Customer) = New HashSet(Of Customer)
    Public Overridable Property Emp_Attendence As ICollection(Of Emp_Attendence) = New HashSet(Of Emp_Attendence)
    Public Overridable Property Employees As ICollection(Of Employee) = New HashSet(Of Employee)
    Public Overridable Property Floor_Detail As ICollection(Of Floor_Detail) = New HashSet(Of Floor_Detail)
    Public Overridable Property Pay_Roll As ICollection(Of Pay_Roll) = New HashSet(Of Pay_Roll)
    Public Overridable Property User_Type As User_Type
    Public Overridable Property RB_Pay_Detail As ICollection(Of RB_Pay_Detail) = New HashSet(Of RB_Pay_Detail)
    Public Overridable Property RB_Pay As ICollection(Of RB_Pay) = New HashSet(Of RB_Pay)
    Public Overridable Property Sch_Accounts As ICollection(Of Sch_Accounts) = New HashSet(Of Sch_Accounts)
    Public Overridable Property Sch_Accounts1 As ICollection(Of Sch_Accounts) = New HashSet(Of Sch_Accounts)

End Class
