'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Plaza
    Public Property Plaza_ID As Integer
    Public Property Plaza_Name As String

    Public Overridable Property Customers As ICollection(Of Customer) = New HashSet(Of Customer)
    Public Overridable Property Floors As ICollection(Of Floor) = New HashSet(Of Floor)

End Class
