'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RB_Pay_Per
    Public Property RB_Pay_Per_ID As Integer
    Public Property RB_Pay_Per_FoRate As Nullable(Of Decimal)
    Public Property RB_Pay_Per_ToRate As Nullable(Of Decimal)
    Public Property RB_Pay_Per_Cent As Nullable(Of Double)

End Class
