'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RB_Pay_Detail
    Public Property RB_Pay_Detail_ID As Integer
    Public Property Cus_ID As Nullable(Of Integer)
    Public Property RB_Pay_Detail_Shop_Code As String
    Public Property RB_Pay_Detail_Invoice As String
    Public Property RB_Pay_Detail_Receipt As String
    Public Property RB_Pay_Detail_IssueDate As Nullable(Of Date)
    Public Property RB_Pay_Detail_LastDate As Nullable(Of Date)
    Public Property RB_Pay_Detail_PayDate As Nullable(Of Date)
    Public Property RB_Pay_Detail_Used_Unit As Nullable(Of Double)
    Public Property RB_Pay_Detail_Unit_Price As Nullable(Of Double)
    Public Property RB_Pay_Detail_Bill_Amt As Nullable(Of Double)
    Public Property RB_Pay_Detail_Tax_Percent As Nullable(Of Double)
    Public Property RB_Pay_Detail_Tax_Unit As Nullable(Of Double)
    Public Property RB_Pay_Detail_Tax_Amt As Nullable(Of Double)
    Public Property RB_Pay_Detail_TBill As Nullable(Of Double)
    Public Property RB_Pay_Detail_TBill_Account_ID As Nullable(Of Integer)
    Public Property RB_Pay_Detail_Gas_Used_Unit As Nullable(Of Double)
    Public Property RB_Pay_Detail_Gas_Unit_Price As Nullable(Of Double)
    Public Property RB_Pay_Detail_Gas_TBill As Nullable(Of Double)
    Public Property RB_Pay_Detail_Gas_TBill_Account_ID As Nullable(Of Integer)
    Public Property RB_Pay_Detail_Rent As Nullable(Of Double)
    Public Property RB_Pay_Detail_Rent_Account_ID As Nullable(Of Integer)
    Public Property RB_Pay_Detail_Fine As Nullable(Of Double)
    Public Property RB_Pay_Detail_Fine_Account_ID As Nullable(Of Integer)
    Public Property RB_Pay_Detail_Receivable_Account_ID As Nullable(Of Integer)
    Public Property RB_Pay_Detail_Payable As Nullable(Of Double)
    Public Property RB_Pay_Detail_Paid As Nullable(Of Double)
    Public Property RB_Pay_Detail_Paid_Account_ID As Nullable(Of Integer)
    Public Property RB_Pay_Detail_Due As Nullable(Of Double)
    Public Property RB_Pay_Detail_Status As String
    Public Property RB_Pay_Detail_Rent_Update As String
    Public Property User_ID As Nullable(Of Integer)

    Public Overridable Property Chart_Of_Accounts As Chart_Of_Accounts
    Public Overridable Property Chart_Of_Accounts1 As Chart_Of_Accounts
    Public Overridable Property Chart_Of_Accounts2 As Chart_Of_Accounts
    Public Overridable Property Chart_Of_Accounts3 As Chart_Of_Accounts
    Public Overridable Property Chart_Of_Accounts4 As Chart_Of_Accounts
    Public Overridable Property Chart_Of_Accounts5 As Chart_Of_Accounts
    Public Overridable Property Chart_Of_Accounts_Detail As ICollection(Of Chart_Of_Accounts_Detail) = New HashSet(Of Chart_Of_Accounts_Detail)
    Public Overridable Property Customer As Customer
    Public Overridable Property Plaza_User As Plaza_User
    Public Overridable Property RB_Pay_Detail_Payments As ICollection(Of RB_Pay_Detail_Payments) = New HashSet(Of RB_Pay_Detail_Payments)

End Class
