'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RB_Pay_Detail_Payments
    Public Property RB_Pay_Detail_Payments_ID As Integer
    Public Property RB_Pay_Detail_ID As Nullable(Of Integer)
    Public Property RB_Pay_Detail_Payments_Receipt As String
    Public Property RB_Pay_Detail_Payments_Date As Nullable(Of Date)
    Public Property RB_Pay_Detail_Payments_Amt As Nullable(Of Double)

    Public Overridable Property RB_Pay_Detail As RB_Pay_Detail

End Class
