'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Rent_Cash_Account
    Public Property Rent_Cash_Account_ID As Integer
    Public Property Chart_Of_Accounts_ID As Nullable(Of Integer)

    Public Overridable Property Chart_Of_Accounts As Chart_Of_Accounts

End Class
