'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Shop_Type
    Public Property Shop_Type_ID As Integer
    Public Property Shop_Type1 As String
    Public Property Shop_Rent_Update As String

    Public Overridable Property Shops As ICollection(Of Shop) = New HashSet(Of Shop)

End Class
