'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Shop
    Public Property Shop_ID As Integer
    Public Property Shop_Floor_ID As Nullable(Of Integer)
    Public Property Shop_Type_ID As Nullable(Of Integer)
    Public Property Shop_Code As String
    Public Property Shop_Rate As Nullable(Of Decimal)
    Public Property Shop_Meter_No As String
    Public Property Shop_Status As Nullable(Of Boolean)
    Public Property Shop_Meter_Unit_Price As Nullable(Of Double)
    Public Property Shop_Meter_Last_Reading As Nullable(Of Double)
    Public Property Shop_Gas_Meter_No As String
    Public Property Shop_Gas_Meter_Unit_Price As Nullable(Of Double)
    Public Property Shop_Gas_Meter_Last_Reading As Nullable(Of Double)

    Public Overridable Property Customer_Bridge As ICollection(Of Customer_Bridge) = New HashSet(Of Customer_Bridge)
    Public Overridable Property Floor As Floor
    Public Overridable Property Shop_Type As Shop_Type

End Class
