'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Unit_Type
    Public Property Unit_Type_ID As Integer
    Public Property Unit_Type1 As String

    Public Overridable Property Customer_Bridge As ICollection(Of Customer_Bridge) = New HashSet(Of Customer_Bridge)

End Class
