'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Veh_Maintinance
    Public Property Veh_Maintinance_ID As Integer
    Public Property Vehicle_ID As Nullable(Of Integer)
    Public Property Veh_Maintinance_Invoice As String
    Public Property Veh_Maintinance_Date As Nullable(Of Date)
    Public Property Veh_Expensee_Type_ID As Nullable(Of Integer)
    Public Property Veh_Maintinance_Workshop As String
    Public Property Veh_Maintinance_Repairing_Amount As Nullable(Of Decimal)
    Public Property Veh_Maintinance_Parts As String
    Public Property Veh_Maintinance_Amount As Nullable(Of Decimal)

    Public Overridable Property Veh_Expensee_Type As Veh_Expensee_Type
    Public Overridable Property Vehicle As Vehicle

End Class
