'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Veh_Fuel_Detail
    Public Property Veh_Fuel_Detail_ID As Integer
    Public Property Vehicle_ID As Nullable(Of Integer)
    Public Property Fuel_Pump_ID As Nullable(Of Integer)
    Public Property Veh_Fuel_Detail_Invoice As String
    Public Property Veh_Fuel_Detail_Date As Nullable(Of Date)
    Public Property Veh_Fuel_Detail_Start_MR As Nullable(Of Double)
    Public Property Veh_Fuel_Detail_Last_MR As Nullable(Of Double)
    Public Property Veh_Fuel_Detail_Liter As Nullable(Of Decimal)
    Public Property Veh_Fuel_Detail_Amount As Nullable(Of Decimal)
    Public Property Veh_Fuel_Detail_Per_Liter As Nullable(Of Decimal)

    Public Overridable Property Fuel_Pump As Fuel_Pump
    Public Overridable Property Vehicle As Vehicle

End Class
