'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Veh_Expensee_Type
    Public Property Veh_Expensee_Type_ID As Integer
    Public Property Veh_Expensee_Type_Name As String

    Public Overridable Property Veh_Maintinance As ICollection(Of Veh_Maintinance) = New HashSet(Of Veh_Maintinance)

End Class
