'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vehicle
    Public Property Vehicle_ID As Integer
    Public Property Veh_Type_ID As Nullable(Of Integer)
    Public Property Vehicle_Company As String
    Public Property Vehicle_Reg_No As String
    Public Property Vehicle_Model As String
    Public Property Veh_Fuel_Type_ID As Nullable(Of Integer)
    Public Property Vehicle_Plate_No As String
    Public Property Vehicle_Start_MR As String
    Public Property Vehicle_Status As Nullable(Of Boolean)

    Public Overridable Property Emb_Calls As ICollection(Of Emb_Calls) = New HashSet(Of Emb_Calls)
    Public Overridable Property Veh_Fuel_Detail As ICollection(Of Veh_Fuel_Detail) = New HashSet(Of Veh_Fuel_Detail)
    Public Overridable Property Veh_Fuel_Type As Veh_Fuel_Type
    Public Overridable Property Veh_Maintinance As ICollection(Of Veh_Maintinance) = New HashSet(Of Veh_Maintinance)
    Public Overridable Property Veh_Type As Veh_Type

End Class
