'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emp_Bio_Device_Users
    Public Property Emp_ID As Integer
    Public Property Attendence_Status_ID As Nullable(Of Integer)
    Public Property Emp_Bio_Device_Users_UserID As Integer
    Public Property Emp_Bio_Device_User_Name As String
    Public Property Emp_Bio_Device_User_Finger As Nullable(Of Integer)
    Public Property Emp_Bio_Device_User_tmpData As String
    Public Property Emp_Bio_Device_User_Privilege As Nullable(Of Integer)
    Public Property Emp_Bio_Device_User_Password As String
    Public Property Emp_Bio_Device_User_FacetmpData As String
    Public Property Emp_Bio_Device_User_iLength As Nullable(Of Integer)
    Public Property Emp_Bio_Device_User_Enabled As Nullable(Of Boolean)

    Public Overridable Property Attendence_Status As Attendence_Status
    Public Overridable Property Emp_Attendence_Device As ICollection(Of Emp_Attendence_Device) = New HashSet(Of Emp_Attendence_Device)
    Public Overridable Property Employee As Employee

End Class
