'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emp_Att_Payment
    Public Property Emp_Att_Payment_ID As Integer
    Public Property Emp_ID As Nullable(Of Integer)
    Public Property Emp_Att_Payment_Issue_Date As Nullable(Of Date)
    Public Property Emp_Att_Payment_From_Date As Nullable(Of Date)
    Public Property Emp_Att_Payment_To_Date As Nullable(Of Date)
    Public Property Emp_Att_Payment_DutyOn As String
    Public Property Emp_Att_Payment_DutyOff As String
    Public Property Emp_Att_Payment_DutyFriOff As String
    Public Property Emp_Att_Payment_Total_Hours As String
    Public Property Emp_Att_Payment_Total_MonthDays As Nullable(Of Double)
    Public Property Emp_Att_Payment_Total_OffDays As Nullable(Of Double)
    Public Property Emp_Att_Payment_Total_OffDays_Amount As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Total_Days As Nullable(Of Double)
    Public Property Emp_Att_Payment_Total_Salaray_Days As Nullable(Of Double)
    Public Property Emp_Att_Payment_Total_DayRate As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Total_MinRate As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_ExtraDays As Nullable(Of Double)
    Public Property Emp_Att_Payment_ExtraDays_Amount As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Absent_D As Nullable(Of Double)
    Public Property Emp_Att_Payment_Absent_Amount As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_InOutDays As Nullable(Of Double)
    Public Property Emp_Att_Payment_InOutDays_Amount As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Salaray_Total As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Late_H As String
    Public Property Emp_Att_Payment_Late_D As Nullable(Of Double)
    Public Property Emp_Att_Payment_Late_Amount As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Early_H As String
    Public Property Emp_Att_Payment_Early_D As Nullable(Of Double)
    Public Property Emp_Att_Payment_Early_Amount As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_OverTime_H As String
    Public Property Emp_Att_Payment_OverTime_D As Nullable(Of Double)
    Public Property Emp_Att_Payment_OverTime_Amount As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Private_Late_H As String
    Public Property Emp_Att_Payment_Private_Late_D As Nullable(Of Double)
    Public Property Emp_Att_Payment_Private_Late_D_T As Nullable(Of Double)
    Public Property Emp_Att_Payment_Private_Late_Amount As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Short_H As String
    Public Property Emp_Att_Payment_Short_D As Nullable(Of Double)
    Public Property Emp_Att_Payment_Short_D_T As Nullable(Of Double)
    Public Property Emp_Att_Payment_Short_Amount As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Lunch_Late_H As String
    Public Property Emp_Att_Payment_Lunch_Late_D As Nullable(Of Double)
    Public Property Emp_Att_Payment_Lunch_Late_D_T As Nullable(Of Double)
    Public Property Emp_Att_Payment_Lunch_Late_Amount As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Lunch_OverTime_H As String
    Public Property Emp_Att_Payment_Lunch_OverTime_D As Nullable(Of Double)
    Public Property Emp_Att_Payment_Lunch_OverTime_Amount As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Prayer_Late_H As String
    Public Property Emp_Att_Payment_Prayer_Late_D As Nullable(Of Double)
    Public Property Emp_Att_Payment_Prayer_Late_D_T As Nullable(Of Double)
    Public Property Emp_Att_Payment_Prayer_Late_Amount As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Add_Days As Nullable(Of Double)
    Public Property Emp_Att_Payment_Late As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Fix As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Beg As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Advance As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Amount As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Fine As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Bonus As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Total As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Paid As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Balance As Nullable(Of Decimal)

    Public Overridable Property Employee As Employee

End Class
