'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee
    Public Property Emp_ID As Integer
    Public Property Emp_Reg As String
    Public Property Emp_Pass As String
    Public Property Emp_Name As String
    Public Property Emp_Father As String
    Public Property Emp_Phone As String
    Public Property Emp_Phone2 As String
    Public Property Emp_Address As String
    Public Property Emp_Quali As String
    Public Property Emp_Designation As String
    Public Property Emp_Report_To As Nullable(Of Integer)
    Public Property Emp_Date_Hired As Nullable(Of Date)
    Public Property Emp_Date_Terminated As Nullable(Of Date)
    Public Property Emp_Date_ReHired As Nullable(Of Date)
    Public Property Emp_Birth_Date As Nullable(Of Date)
    Public Property Emp_NIC_No As String
    Public Property Emp_Beg_Balance As Nullable(Of Double)
    Public Property Emp_Status As Nullable(Of Boolean)
    Public Property Emp_DutyOn As String
    Public Property Emp_Duty_Off As String
    Public Property Emp_Salary As Nullable(Of Double)
    Public Property User_ID As Integer

    Public Overridable Property Emp_Att_Payment As ICollection(Of Emp_Att_Payment) = New HashSet(Of Emp_Att_Payment)
    Public Overridable Property Emp_Attendence_Device As ICollection(Of Emp_Attendence_Device) = New HashSet(Of Emp_Attendence_Device)
    Public Overridable Property Emp_Bio_Device_Users As ICollection(Of Emp_Bio_Device_Users) = New HashSet(Of Emp_Bio_Device_Users)
    Public Overridable Property Plaza_User As Plaza_User

End Class
