'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emp_Att_Payment
    Public Property Emp_Att_Payment_ID As Integer
    Public Property Emp_ID As Nullable(Of Integer)
    Public Property Emp_Att_Payment_Issue_Date As Nullable(Of Date)
    Public Property Emp_Att_Payment_From_Date As Nullable(Of Date)
    Public Property Emp_Att_Payment_To_Date As Nullable(Of Date)
    Public Property Emp_Att_Payment_Add_Days As Nullable(Of Double)
    Public Property Emp_Att_Payment_Late As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Fix As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Beg As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Advance As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Amount As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Fine As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Bonus As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Total As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Paid As Nullable(Of Decimal)
    Public Property Emp_Att_Payment_Balance As Nullable(Of Decimal)

    Public Overridable Property Employee As Employee

End Class
