'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Emp_Attendence_Device
    Public Property Emp_Attendence_Device_ID As Integer
    Public Property Emp_ID As Nullable(Of Integer)
    Public Property Attendence_Status_ID As Nullable(Of Integer)
    Public Property Emp_Attendence_Device_Date As Nullable(Of Date)
    Public Property Emp_Attendence_Device_Time As String
    Public Property Emp_Attendence_Device_Cal1 As String
    Public Property Emp_Attendence_Device_Cal2 As String
    Public Property Emp_Attendence_Device_Cal3 As String
    Public Property Emp_Attendence_Device_Cal4 As String
    Public Property Emp_Attendence_Device_Cal5 As String
    Public Property Emp_Attendence_Device_Cal6 As String
    Public Property Emp_Attendence_Device_Cal7 As String
    Public Property User_ID As Nullable(Of Integer)

    Public Overridable Property Attendence_Status As Attendence_Status
    Public Overridable Property Employee As Employee

End Class
