Imports System.Data.Entity
Public Class frmEmployeeEdit

    Dim db As New CsmdBioAttendenceEntities '= New CsmdBioAttendenceEntities()

    Sub New()
        InitializeComponent()
        db.Employees.Load()
        BindingSource1.DataSource = db.Employees.Local.ToBindingList()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Instantiate a new DBContext

    End Sub

    Private Sub BarButtonItem1_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem1.ItemClick
        AdvBandedGridView1.AddNewRow()
    End Sub

    Private Sub AdvBandedGridView1_RowUpdated(sender As Object, e As DevExpress.XtraGrid.Views.Base.RowObjectEventArgs) Handles AdvBandedGridView1.RowUpdated
        db.SaveChanges()
    End Sub

    Private Sub BarButtonItem3_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem3.ItemClick
        AdvBandedGridView1.OptionsBehavior.Editable = True
        BarButtonItem5.Enabled = True
    End Sub

    Private Sub BarButtonItem6_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem6.ItemClick
        AdvBandedGridView1.OptionsBehavior.Editable = False
        db.Employees.Load()
        BindingSource1.DataSource = db.Employees.Local.ToBindingList()
        BarButtonItem5.Enabled = False
    End Sub

    Private Sub BarButtonItem4_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem4.ItemClick
        Me.Close()
    End Sub

    Private Sub BarButtonItem5_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem5.ItemClick
        Try
            AdvBandedGridView1.DeleteSelectedRows()
            db.SaveChanges()
        Catch ex As Exception

        End Try
    End Sub

    Private Sub BarButtonItem11_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BarButtonItem11.ItemClick
        AdvBandedGridView1.ShowRibbonPrintPreview()
    End Sub
End Class
