Imports DevExpress.XtraBars
Imports System.Runtime.InteropServices
Imports DevExpress.XtraEditors
Imports DevExpress.XtraEditors.Camera
Imports System.IO
Imports System.Drawing.Imaging
Imports System.Data.Entity
Imports DevExpress.XtraBars.Navigation

Public Class frmEmployeesAdd

    'Sub New()

    '    InitializeComponent()
    '    ' This line of code is generated by Data Source Configuration Wizard
    '    ' Instantiate a new DBContext
    '    Dim dbContext As School.CsmdBioAttendenceEntities = New School.CsmdBioAttendenceEntities()
    '    ' Call the Load method to get the data for the given DbSet from the database.
    '    dbContext.Employees.Load()
    '    ' This line of code is generated by Data Source Configuration Wizard
    '    BindingSource1.DataSource = dbContext.Employees.Local.ToBindingList()
    'End Sub
    Dim db As New CsmdBioAttendenceEntities
    'Dim Load_cmb_Emp_Designation As New cmb_Emp_Designation
    'Dim Load_cmb_Emp_Title_ID As New cmb_Emp_Title_ID
    'Dim LoadAddress As New cmbAddress_Detail
    'Dim LoadStuNicType As New cmbStuNicType
    'Dim Load_cmb_Stu_Source_Travel_ID As New cmb_Stu_Source_Travel_ID
    Dim Load_cmb_Employee_Search_Look As New cmb_Employee_Search_Look
    'Dim Load_cmb_Driver_Short_Record As New cmb_Driver_Short_Record_Teac
    'Dim Load_cmbClassRoom As New cmbClassRoom

    Dim Load_cmb_Emp_Report_To As New cmb_Emp_Report_To
    'Dim Load_cmb_Emp_Marital_Status As New cmb_Emp_Marital_Status
    'Dim Load_cmb_Emp_Pay_Frequency As New cmb_Emp_Pay_Frequency
    'Dim Load_cmb_Emp_Pay_Method As New cmb_Emp_Pay_Method

    'Dim Load_cmb_Emp_Pay_Method_Default As New cmb_Emp_Pay_Method_Default
    'Dim Load_cmb_Chart_Of_Accounts_ID As New cmb_Chart_Of_Accounts_ID
    'cmb_Emp_Report_To
    'cmb_Emp_Marital_Status
    'cmb_Emp_Pay_Frequency
    'cmb_Emp_Pay_Method
    Dim ghj As Integer
    <DllImport("kernel32")>
    Public Shared Function Beep(ByVal dwFreg As Integer, ByVal dwDuration As Integer) As Integer
    End Function

#Region "TEACHER MODIFIED VIEWER frmTeacherAdd_LOAD"
    Private Sub frmTeacherAdd_Load(sender As Object, e As EventArgs) Handles Me.Load

        'Load_cmbClassRoom.ColumnsAndData(Emp_Class_Inchargeship_ID)
        Load_cmb_Employee_Search_Look.ColumnsAndData(SearchLookUpEdit1)

        'Load_cmb_Stu_Source_Travel_ID.ColumnsAndData(Student_Source_Travel_ID)
        'Load_cmb_Emp_Title_ID.ColumnsAndData(Emp_Title_ID)
        'LoadAddress.ColumnsAndData(Emp_Address_ID)
        'LoadStuNicType.ColumnsAndData(Emp_NIC_ID)
        'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        Load_cmb_Emp_Report_To.ColumnsAndData(Emp_Report_To)
        'Load_cmb_Emp_Marital_Status.ColumnsAndData(Emp_Marital_Status_ID)
        'Load_cmb_Emp_Pay_Frequency.ColumnsAndData(Emp_Pay_Frequency_ID)
        'Load_cmb_Emp_Pay_Method.ColumnsAndData(Emp_Pay_Method_ID)
        'Load_cmb_Emp_Pay_Method_Default.ColumnsAndData(RepositoryItemLookUpEdit1, 1)
        'Load_cmb_Chart_Of_Accounts_ID.ColumnsAndData(RepositoryItemLookUpEdit2)
        'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        'LoadUcControl(Text)
        'AxZKFPEngX1.InitEngine()
        'If AxZKFPEngX1.InitEngine() = 0 Then
        '    AxZKFPEngX1.InitEngine()
        'Else
        '    AxZKFPEngX1.EndEngine()
        '    MsgBox("failed")
        'End If
        'Load_cmb_Emp_Designation.ColumnsAndData(Emp_Designation_ID)
        ' ''If frmLoadAction = frmNewAction Then
        ' ''    NewStudentData()

        ' ''ElseIf frmLoadAction = frmEditAction Then
        ' ''    'intMultiGrid = 7
        ' ''    'LoadCategory()
        ' ''    'CmbSupplierMaster.ColumnsAndData(Txt_Supplier_Load)
        ' ''    LoadTeachersRecords(intMultiGrid)
        ' ''    'LoadValidate()
        ' ''End If

        LoadTile()
    End Sub
#End Region


#Region "TEACHER ADD NEW RECORD"


    Public Sub NewStudentData()
        ''For Each textEdit As Control In Me.LayoutControl1.Controls
        ''    If TypeOf textEdit Is TextEdit Then
        ''        TryCast(textEdit, TextEdit).ResetText()
        ''    End If
        ''Next textEdit
        ''For Each textEdit As Control In Me.LayoutControl2.Controls
        ''    If TypeOf textEdit Is TextEdit Then
        ''        TryCast(textEdit, TextEdit).ResetText()
        ''    End If
        ''Next textEdit

        'ButtonAction(NewButton)
        ''CmbSupplier.ColumnsAndData(Txt_Supplier_Load)
        'ResetBut.Enabled = True
        'GridControl1.DataSource = Nothing
        Emp_Reg.Properties.ReadOnly = True
        'Txt_Supplier_Load.Enabled = True
        Emp_Reg.Text = AutoRegisterNumber()
        Emp_Date_Join.EditValue = Today
        Emp_Image.Image = Image.FromFile(Application.StartupPath & "\Images\Empty.jpg")
        Using Db As New CsmdBioAttendenceEntities
            Dim hh = (From a In Db.Employees Where a.Emp_Reg = Emp_Reg.Text Select a).FirstOrDefault
            If hh IsNot Nothing Then
                LoadTeachersRecords(hh.Emp_ID)
            End If
        End Using
    End Sub
#End Region

#Region "TEACHER RECORDS SAVE AND UPDATE FUNCTION"
    Public Sub SaveAndUpdateData()
        Using db As New CsmdBioAttendenceEntities
            'Dim finger As String = AxZKFPEngX1.GetTemplateAsString()
            If Not Emp_Address_ID.EditValue = Nothing Then


                Dim Tea = (From a In db.Employees Where a.Emp_Reg = Emp_Reg.Text Select a).FirstOrDefault
                If Not IsNothing(Tea) Then
                    With Tea
                        .Emp_Name = Emp_Name.Text
                        .Emp_Father = Emp_Father.Text
                        .Emp_Phone = Emp_Phone.Text
                        .Emp_Phone2 = Emp_Phone2.Text
                        .Emp_Address = Emp_Address_ID.EditValue
                        .Emp_Quali = Emp_Quali.Text
                        .Emp_Designation = Emp_Designation_ID.EditValue
                        '.Emp_Class_Inchargeship_ID = Emp_Class_Inchargeship_ID.EditValue
                        .Emp_Date_Hired = Emp_Date_Join.EditValue
                        .Emp_Date_Terminated = Emp_Date_Leave.EditValue
                        .Emp_Date_ReHired = Emp_Date_ReHired.EditValue
                        .Emp_Image = ImgToByteArray(Emp_Image.Image, ImageFormat.Png)
                        'If CheckEdit1.Checked = True Then
                        '    .Emp_Finger_Image = ImgToDb(New FileInfo("d:\ls_l1b.jpg"))
                        '    .Emp_Finger_Code = finger
                        '    MsgBox("jj")
                        'End If
                        Try
                            .Emp_Signature = ImgToByteArray(Emp_Signature.Image, ImageFormat.Png)
                        Catch ex As Exception

                        End Try
                        '.Emp_Title_ID = Emp_Title_ID.EditValue
                        '.Emp_NIC_ID = Emp_NIC_ID.EditValue
                        .Emp_NIC_No = Emp_NIC_No.EditValue
                        .Emp_Report_To = Emp_Report_To.EditValue
                        .Emp_Birth_Date = Emp_Birth_Date.EditValue

                        '.Emp_Marital_Status_ID = Emp_Marital_Status_ID.EditValue
                        '.Emp_Husband_Name = Emp_Husband_Name.Text
                        .Emp_Status = Emp_Status.Checked

                        .User_ID = PlazaUserID

                        'Dim gg As Integer = Emp_Pay_Method_ID.EditValue
                        'Dim dtE = (From a In .Emp_Pay Where a.Emp_Pay_Method_ID = gg Select a).FirstOrDefault
                        'If dtE IsNot Nothing Then
                        '    With dtE
                        '        .Emp_ID = Tea.Emp_ID
                        '        .Emp_Pay_Method_ID = Emp_Pay_Method_ID.EditValue
                        '        .Emp_Pay_Frequency_ID = Emp_Pay_Frequency_ID.EditValue
                        '        .Student_Source_Travel_ID = Student_Source_Travel_ID.EditValue
                        '        .Drv_ID = Drv_ID.EditValue
                        '    End With
                        'Else
                        '    Dim dtEnew = New Emp_Pay
                        '    With dtEnew
                        '        .Emp_ID = Tea.Emp_ID
                        '        .Emp_Pay_Method_ID = Emp_Pay_Method_ID.EditValue
                        '        .Emp_Pay_Frequency_ID = Emp_Pay_Frequency_ID.EditValue
                        '        .Student_Source_Travel_ID = Student_Source_Travel_ID.EditValue
                        '        .Drv_ID = Drv_ID.EditValue
                        '    End With
                        '    db.Emp_Pay.Add(dtEnew)
                        'End If

                        db.SaveChanges()

                        'Dim Custom_Fields = (From a In db.Emp_Custom_Fields Where a.Emp_ID = ghj Select a).ToList
                        'If Custom_Fields.Count() > 0 Then
                        '    'Dim k As Integer = 0
                        '    For k As Integer = 0 To GridView3.RowCount - 1
                        '        With Custom_Fields.Item(k)
                        '            '.Emp_Custom_Fields_Default_ID = GridView10.GetRowCellValue(k, "FieldName")
                        '            .Emp_Custom_Fields_Default_Text = GridView3.GetRowCellValue(k, "Emp_Custom_Fields_Default_Text")
                        '        End With

                        '        db.SaveChanges()
                        '    Next
                        'Else
                        '    Dim Custom_Fields_Add = New Emp_Custom_Fields
                        '    For X As Integer = 0 To GridView3.RowCount - 1
                        '        With Custom_Fields_Add
                        '            .Emp_ID = ghj
                        '            '.Emp_Custom_Fields_Default.Emp_Custom_Fields_Default_ID = GridView2.GetRowCellValue(M, "FieldName")
                        '            .Emp_Custom_Fields_Default_ID = GridView3.GetRowCellValue(X, "Emp_Custom_Fields_Default_ID")   'GridView10.GetRowCellValue(X, "FieldName")
                        '            .Emp_Custom_Fields_Default_Text = GridView3.GetRowCellValue(X, "Emp_Custom_Fields_Default_Text")
                        '            'M += 1
                        '        End With
                        '        db.Emp_Custom_Fields.Add(Custom_Fields_Add)
                        '        db.SaveChanges()
                        '    Next
                        'End If
                    End With
                    'My.Computer.Audio.Play("Sounds\Windows Print complete.wav")
                    XtraMessageBox.Show("Update Employee Successfull")
                    LoadTile()
                Else
                    Dim TeaNew = New Employee
                    With TeaNew
                        .Emp_Reg = Emp_Reg.Text
                        .Emp_Name = Emp_Name.Text
                        .Emp_Father = Emp_Father.Text
                        .Emp_Phone = Emp_Phone.Text
                        .Emp_Phone2 = Emp_Phone2.Text
                        .Emp_Address = Emp_Address_ID.EditValue
                        .Emp_Quali = Emp_Quali.Text
                        .Emp_Designation = Emp_Designation_ID.EditValue
                        '.Emp_Class_Inchargeship_ID = Emp_Class_Inchargeship_ID.EditValue
                        .Emp_Date_Hired = Emp_Date_Join.EditValue
                        .Emp_Date_Terminated = Emp_Date_Leave.EditValue
                        .Emp_Date_ReHired = Emp_Date_ReHired.EditValue
                        .Emp_Image = ImgToByteArray(Emp_Image.Image, ImageFormat.Png)
                        'If CheckEdit1.Checked = True Then
                        '    .Emp_Finger_Image = ImgToDb(New FileInfo("d:\ls_l1b.jpg"))
                        '    .Emp_Finger_Code = finger
                        '    MsgBox("mm")
                        'End If
                        Try
                            .Emp_Signature = ImgToByteArray(Emp_Signature.Image, ImageFormat.Png)
                        Catch ex As Exception

                        End Try
                        '.Emp_Title_ID = Emp_Title_ID.EditValue
                        '.Emp_NIC_ID = Emp_NIC_ID.EditValue
                        .Emp_NIC_No = Emp_NIC_No.EditValue
                        .Emp_Report_To = Emp_Report_To.EditValue
                        .Emp_Birth_Date = Emp_Birth_Date.EditValue

                        '.Emp_Marital_Status_ID = Emp_Marital_Status_ID.EditValue
                        '.Emp_Husband_Name = Emp_Husband_Name.Text
                        .Emp_Status = Emp_Status.Checked

                        .User_ID = PlazaUserID
                        'Dim gg As Integer = Emp_Pay_Method_ID.EditValue
                        'Dim dtE = (From a In .Emp_Pay Where a.Emp_Pay_Method_ID = gg Select a).FirstOrDefault
                        'If dtE IsNot Nothing Then
                        '    With dtE
                        '        .Emp_ID = Tea.Emp_ID
                        '        .Emp_Pay_Method_ID = Emp_Pay_Method_ID.EditValue
                        '        .Emp_Pay_Frequency_ID = Emp_Pay_Frequency_ID.EditValue
                        '        .Student_Source_Travel_ID = Student_Source_Travel_ID.EditValue
                        '        .Drv_ID = Drv_ID.EditValue
                        '    End With
                        'Else
                        '    'Dim dtEnew = New Emp_Pay
                        '    'With dtEnew
                        '    '    .Emp_ID = Tea.Emp_ID
                        '    '    .Emp_Pay_Method_ID = Emp_Pay_Method_ID.EditValue
                        '    '    .Emp_Pay_Frequency_ID = Emp_Pay_Frequency_ID.EditValue
                        '    '    .Student_Source_Travel_ID = Student_Source_Travel_ID.EditValue
                        '    '    .Drv_ID = Drv_ID.EditValue
                        '    'End With
                        '    'db.Emp_Pay.Add(dtEnew)
                        'End If

                        'Dim Custom_Fields = New Emp_Custom_Fields
                        'For X As Integer = 0 To GridView3.RowCount - 1
                        '    With Custom_Fields
                        '        .Emp_ID = ghj
                        '        '.Emp_Custom_Fields_Default.Emp_Custom_Fields_Default_ID = GridView2.GetRowCellValue(M, "FieldName")
                        '        .Emp_Custom_Fields_Default_ID = GridView3.GetRowCellValue(X, "Emp_Custom_Fields_Default_ID")   'GridView10.GetRowCellValue(X, "FieldName")
                        '        .Emp_Custom_Fields_Default_Text = GridView3.GetRowCellValue(X, "Emp_Custom_Fields_Default_Text")
                        '        'M += 1
                        '    End With
                        '    db.Emp_Custom_Fields.Add(Custom_Fields)
                        '    db.SaveChanges()
                        'Next

                    End With
                    db.Employees.Add(TeaNew)
                    Dim AddNum = (From a In db.Auto_Number Select a).FirstOrDefault
                    If AddNum IsNot Nothing Then
                        AddNum.Auto_Emp_Num = Replace(Replace(AutoRegisterNumber(), "R-", ""), Microsoft.VisualBasic.Right(Replace(AutoRegisterNumber(), "R-", ""), 3), "")
                    End If
                    'My.Computer.Audio.Play("Sounds\Windows Notify.wav")
                    XtraMessageBox.Show("Add new Employee Successfull")
                    LoadTile()
                End If
                db.SaveChanges()
            Else
                MsgBox("Please select a Address of this Employee")
            End If

           
        End Using
    End Sub
#End Region

#Region "TEACHER RECORDS LOAD"
    Public Sub LoadTeachersRecords(RecordRow As Integer)

        'Try
        Using db As New CsmdBioAttendenceEntities

            Dim LoadStudents = (From a In db.Employees Where a.Emp_ID = RecordRow Select a).FirstOrDefault
            If LoadStudents IsNot Nothing Then
                With LoadStudents
                    ghj = .Emp_ID
                    Try
                        Emp_Image.Image = DbToImg(.Emp_Image)
                    Catch ex As Exception
                        Emp_Image.Image = Image.FromFile(Application.StartupPath & "\Images\Empty.jpg")
                    End Try
                    Emp_Reg.Text = .Emp_Reg
                    Emp_Name.Text = .Emp_Name
                    Emp_Father.Text = .Emp_Father
                    Emp_Phone.Text = .Emp_Phone
                    Emp_Phone2.Text = .Emp_Phone2
                    Emp_Address_ID.EditValue = .Emp_Address
                    Emp_Quali.Text = .Emp_Quali
                    Emp_Designation_ID.EditValue = .Emp_Designation
                    'Emp_Class_Inchargeship_ID.EditValue = .Emp_Class_Inchargeship_ID
                    Emp_Date_Join.EditValue = .Emp_Date_Hired
                    Emp_Date_Leave.EditValue = .Emp_Date_Terminated
                    Emp_Date_ReHired.EditValue = .Emp_Date_ReHired
                    Try

                        Emp_Signature.Image = DbToImg(.Emp_Signature)
                    Catch ex As Exception

                    End Try
                    'Emp_Title_ID.EditValue = .Emp_Title_ID
                    'Emp_NIC_ID.EditValue = .Emp_NIC_ID
                    Emp_NIC_No.EditValue = .Emp_NIC_No
                    Emp_Report_To.EditValue = .Emp_Report_To
                    Emp_Birth_Date.EditValue = .Emp_Birth_Date

                    'Emp_Marital_Status_ID.EditValue = .Emp_Marital_Status_ID
                    'Emp_Husband_Name.Text = .Emp_Husband_Name
                    Emp_Status.Checked = .Emp_Status
                    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                    'Dim dts = (From a In db.Emp_Custom_Fields_Default
                    '           Group Join b In db.Emp_Custom_Fields.Where(Function(o) o.Emp_ID = ghj)
                    '           On a.Emp_Custom_Fields_Default_ID Equals b.Emp_Custom_Fields_Default_ID
                    '           Into z = Group
                    '           From b In z.DefaultIfEmpty()
                    '           Select New With {.Emp_Custom_Fields_Default_ID = a.Emp_Custom_Fields_Default_Caption, b.Emp_Custom_Fields_Default_Text}).ToList
                    'If dts.Count > 0 Then
                    '    GridControl3.DataSource = dts
                    'Else
                    '    GridControl3.DataSource = Nothing
                    'End If
                    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                    'Load_EMP_PayRoll_Jounal()
                    ''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    'Dim dd = (From a In .Emp_Pay Select a).FirstOrDefault
                    'If dd IsNot Nothing Then
                    '    Emp_Pay_Method_ID.EditValue = Nothing
                    '    Emp_Pay_Method_ID.EditValue = dd.Emp_Pay_Method_ID
                    '    Emp_Pay_Frequency_ID.EditValue = dd.Emp_Pay_Frequency_ID
                    '    Student_Source_Travel_ID.EditValue = dd.Student_Source_Travel_ID
                    '    Drv_ID.EditValue = dd.Drv_ID
                    'Else
                    '    Emp_Pay_Method_ID.EditValue = Nothing
                    '    Emp_Pay_Frequency_ID.EditValue = Nothing
                    '    Student_Source_Travel_ID.EditValue = Nothing
                    '    Drv_ID.EditValue = Nothing
                    'End If
                    ''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                    ''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    'Dim kok = (From a In .Emp_Attendence Select a).ToList
                    'If kok.Count > 0 Then
                    '    GridControl1.DataSource = kok
                    'Else
                    '    GridControl1.DataSource = Nothing
                    'End If
                    'ListBoxControl1.Items.Clear()
                    'Dim kop = (From a In .Emp_Attendence Group a By a.Emp_Attendence_Att_Status_ID Into z = Group, aa = Count(a.Emp_Attendence_Att_Status_ID) From bb In z Select bb.Att_Status.Att_Status_Type, aa).ToList.Distinct
                    'If kop.Count > 0 Then
                    '    For Each a In kop
                    '        ListBoxControl1.Items.Add(a.Att_Status_Type & " (" & a.aa & ")")
                    '    Next
                    'End If
                    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                End With

            End If

            'CheckEdit1.Checked = False
            'Stu_Admission_No.Properties.ReadOnly = False
        End Using
        'Catch ex As Exception
        '    XtraMessageBox.Show("See Your Text")
        'End Try
    End Sub
#End Region
    Private savapath As String = ""
    'Private Sub axZKFPEngX1_OnImageReceived(ByVal sender As Object, ByVal e As AxZKFPEngXControl.IZKFPEngXEvents_OnImageReceivedEvent) Handles AxZKFPEngX1.OnImageReceived
    '    ''Dim kkk As Image
    '    ''kkk = Image.FromFile("d:\ls_lb.jpg")
    '    'Dim canvas As Graphics = Emp_Image.CreateGraphics()
    '    'AxZKFPEngX1.PrintImageAt(canvas.GetHdc().ToInt32(), 0, 0, PanelControl1.Width, PanelControl1.Height)
    '    'canvas.Dispose()
    '    'AxZKFPEngX1.SaveBitmap("d:\ls_l1b.jpg")
    '    ''axZKFPEngX1.Refresh()
    '    ''Catch ex As Exception
    '    ''kkk = Image.FromFile("d:\ls_l1b.bmp")
    '    ''End Try


    '    ''PictureEdit1.Image = kkk
    '    'Beep(3000, 100)
    'End Sub

    'Private Sub axZKFPEngX1_OnFeatureInfo(ByVal sender As Object, ByVal e As AxZKFPEngXControl.IZKFPEngXEvents_OnFeatureInfoEvent) Handles AxZKFPEngX1.OnFeatureInfo
    '    'Dim sTemp As String = ""
    '    'Dim j As Integer = 0
    '    'If AxZKFPEngX1.IsRegister Then
    '    '    j = AxZKFPEngX1.EnrollIndex - 1
    '    '    sTemp = "Register status: still press finger " & j.ToString() & " times!"
    '    'End If
    '    'sTemp = sTemp & "Fingerprint quality"
    '    'If e.aQuality <> 0 Then sTemp = sTemp & "not good" Else sTemp = sTemp & "it is good"
    'End Sub

    Private Sub Form2_FormClosed(ByVal sender As Object, ByVal e As FormClosedEventArgs) Handles MyBase.FormClosed
        'Try
        '    AxZKFPEngX1.EndEngine()
        'Catch ex As Exception

        'End Try
    End Sub

    'Private Sub axZKFPEngX1_OnCapture(ByVal sender As Object, ByVal e As AxZKFPEngXControl.IZKFPEngXEvents_OnCaptureEvent) Handles AxZKFPEngX1.OnCapture
    '    'Using db As New CsmdBioAttendenceEntities
    '    '    If CheckEdit1.Checked = False Then
    '    '        Emp_Reg.Text = ""
    '    '        Emp_Name.Text = ""
    '    '        Emp_Father.Text = ""
    '    '        Emp_Phone.Text = ""
    '    '        Emp_Address_ID.Text = ""
    '    '        Emp_Quali.Text = ""
    '    '        Emp_Designation_ID.EditValue = Nothing
    '    '        'Emp_Salry.Text = 0
    '    '        Emp_Status.Checked = False
    '    '        Emp_Date_Join.EditValue = Today
    '    '        Emp_Date_Leave.EditValue = Nothing
    '    '    End If
    '    '    Dim temp As Boolean = False
    '    '    Dim Ntemp As String = AxZKFPEngX1.GetTemplateAsString()
    '    '    'Dim uName As Integer = txtName.EditValue
    '    '    Dim dt = (From a In db.Employees Select a).ToList
    '    '    If dt.Count > 0 Then
    '    '        For Each aa In dt
    '    '            Dim Ofinger As String = If(aa.Emp_Finger_Code IsNot Nothing, aa.Emp_Finger_Code, "Finger")
    '    '            If AxZKFPEngX1.VerFingerFromStr(Ofinger, Ntemp, False, temp) Then
    '    '                With aa
    '    '                    If CheckEdit1.Checked = False Then
    '    '                        Try
    '    '                            Emp_Image.Image = DbToImg(.Emp_Image) ' Image.FromFile(Application.StartupPath & "\Images\Teachers\" & .Emp_Reg & ".jpg")
    '    '                        Catch ex As Exception
    '    '                            Emp_Image.Image = Image.FromFile(Application.StartupPath & "\Images\Empty.jpg")
    '    '                        End Try
    '    '                        Emp_Reg.Text = .Emp_Reg
    '    '                        Emp_Name.Text = .Emp_Name
    '    '                        Emp_Father.Text = .Emp_Father
    '    '                        Emp_Phone.Text = .Emp_Phone
    '    '                        Emp_Phone2.Text = .Emp_Phone2
    '    '                        Emp_Address_ID.Text = .Address.Stu_Address_Name
    '    '                        Emp_Quali.Text = .Emp_Quali
    '    '                        Emp_Designation_ID.EditValue = .Emp_Designation_ID
    '    '                        Emp_Class_Inchargeship_ID.EditValue = .Emp_Class_Inchargeship_ID
    '    '                        Emp_Date_Join.EditValue = .Emp_Date_Hired
    '    '                        Emp_Date_Leave.EditValue = .Emp_Date_Terminated
    '    '                        Emp_Date_ReHired.EditValue = .Emp_Date_ReHired
    '    '                        Emp_Signature.Image = DbToImg(.Emp_Signature)

    '    '                        Emp_Gender_ID.EditValue = .Emp_Gender_ID
    '    '                        Emp_NIC_ID.EditValue = .Emp_NIC_ID
    '    '                        Emp_NIC_No.EditValue = .Emp_NIC_No
    '    '                        Emp_Report_To.EditValue = .Emp_Report_To
    '    '                        Emp_Birth_Date.EditValue = .Emp_Birth_Date

    '    '                        Emp_Marital_Status_ID.EditValue = .Emp_Marital_Status_ID
    '    '                        Emp_Husband_Name.Text = .Emp_Husband_Name
    '    '                        Emp_Status.Checked = .Emp_Status
    '    '                    End If
    '    '                End With
    '    '            End If
    '    '        Next
    '    '    End If
    '    'End Using
    'End Sub


    Private Sub RibbonControl1_ItemClick(sender As Object, e As ItemClickEventArgs) Handles RibbonControl1.ItemClick
        'ClickSound()
    End Sub

    Private Sub CloseBut_ItemClick(sender As Object, e As ItemClickEventArgs) Handles CloseBut.ItemClick
        Me.Close()
    End Sub

    Private Sub SaveBut_ItemClick(sender As Object, e As ItemClickEventArgs) Handles SaveBut.ItemClick
        SaveAndUpdateData()
    End Sub

    Private Sub NewBut_ItemClick(sender As Object, e As ItemClickEventArgs) Handles NewBut.ItemClick
        NewStudentData()
    End Sub

    Private Sub ResetBut_ItemClick(sender As Object, e As ItemClickEventArgs) Handles ResetBut.ItemClick

    End Sub

    Private Sub RefreshBut_ItemClick(sender As Object, e As ItemClickEventArgs) Handles RefreshBut.ItemClick
        Load_cmb_Employee_Search_Look.ColumnsAndData(SearchLookUpEdit1)
        'LoadAddress.ColumnsAndData(Emp_Address_ID)
        LoadTeachersRecords(intMultiFee)
        LoadTile()
    End Sub

    'Private Sub SearchLookUpEdit1_EditValueChanged(sender As Object, e As EventArgs)
    '    LoadTeachersRecords(SearchLookUpEdit1.EditValue)
    'End Sub

    Private Sub BindingSource1_CurrentChanged(sender As Object, e As EventArgs) Handles BindingSource1.CurrentChanged

    End Sub

    'Private Sub Student_Source_Travel_ID_EditValueChanged(sender As Object, e As EventArgs) Handles Student_Source_Travel_ID.EditValueChanged
    '    Using db As New CsmdBioAttendenceEntities
    '        Dim k As Integer = Student_Source_Travel_ID.EditValue
    '        Dim dt = (From a In db.Student_Source_Travel Where a.Student_Source_Travel_ID = k Select a.Student_Source_Travel_Type).FirstOrDefault
    '        If dt IsNot Nothing Then
    '            If dt.Contains("Van") Then
    '                Load_cmb_Driver_Short_Record.ColumnsAndData(Drv_ID, k)
    '                Drv_ID.Properties.ReadOnly = False
    '                'Emp_Rent_Scale.Properties.ReadOnly = False
    '            Else
    '                If dt.Contains("Raksha") Then
    '                    Load_cmb_Driver_Short_Record.ColumnsAndData(Drv_ID, k)
    '                    Drv_ID.Properties.ReadOnly = False
    '                    'Emp_Rent_Scale.Properties.ReadOnly = False
    '                Else
    '                    If dt.Contains("Bus") Then
    '                        Load_cmb_Driver_Short_Record.ColumnsAndData(Drv_ID, k)
    '                        Drv_ID.Properties.ReadOnly = False
    '                        'Emp_Rent_Scale.Properties.ReadOnly = False
    '                    Else
    '                        Drv_ID.Properties.ReadOnly = True
    '                        'Emp_Rent_Scale.Properties.ReadOnly = True
    '                        Drv_ID.EditValue = Nothing
    '                        'Emp_Rent_Scale.Text = 0
    '                    End If
    '                End If
    '            End If
    '        End If
    '    End Using
    'End Sub


    Private Sub Emp_Pay_Method_ID_EditValueChanged(sender As Object, e As EventArgs)
        'LoadEditvalueChange()
    End Sub

    'Private Sub LoadPayDetail(IDx As Integer)
    '    Using db As New CsmdBioAttendenceEntities

    '        'Try
    '        Dim gg As Integer = Emp_Pay_Method_ID.EditValue
    '        Dim kmk = (From c In db.Emp_Pay Where c.Emp_Pay_Method_ID = gg And c.Emp_Pay_ID = IDx Select c).FirstOrDefault
    '        If kmk IsNot Nothing Then
    '            'Emp_Pay_Method_ID.EditValue = kmk.Emp_Pay_Method_ID
    '            Emp_Pay_Frequency_ID.EditValue = kmk.Emp_Pay_Frequency_ID
    '            Student_Source_Travel_ID.EditValue = kmk.Student_Source_Travel_ID
    '            Drv_ID.EditValue = kmk.Drv_ID
    '            'Dim hjj As Integer = 102
    '            Dim dta = (From b In db.Emp_Pay_Method_Default Where b.Emp_Pay_Method_ID = gg Select b).ToList
    '            If dta.Count > 0 Then
    '                For Each dtaa In dta
    '                    Dim dtabx = (From a In kmk.Emp_Pay_Detail Where a.Emp_Pay_Method_Default_ID = dtaa.Emp_Pay_Method_Default_ID Select a).FirstOrDefault
    '                    If dtabx IsNot Nothing Then
    '                        'With dtabx
    '                        '    .Emp_Pay_ID = IDx
    '                        '    .Emp_Pay_Method_Default_ID = dtaa.Emp_Pay_Method_Default_ID
    '                        '    .Emp_Pay_Detail_Std = True
    '                        '    .Emp_Pay_Detail_GL_Account_ID = dtaa.Emp_Pay_Salary_Default_GL_Accounts_ID
    '                        '    '.Emp_Pay_Detail_Pay_Rate = 0
    '                        'End With
    '                        'If dtabx.Emp_Pay_Method_Default_ID = dtaa.Emp_Pay_Method_Default_ID And dtabx.Emp_Pay_Method_Default.Emp_Pay_Method_ID = gg Then
    '                        'Else
    '                        '    MsgBox(dtabx.Emp_Pay_Method_Default.Emp_Pay_Salary_Default_FieldName & " " & dtabx.Emp_Pay_Detail_ID)
    '                        '    'db.Emp_Pay_Detail.Remove(fgfg)
    '                        'End If
    '                        'MsgBox(dtabx.Emp_Pay_Method_Default.Emp_Pay_Salary_Default_FieldName & " " & dtabx.Emp_Pay_Detail_ID)
    '                    Else



    '                        Dim ffnew = New Emp_Pay_Detail
    '                        With ffnew
    '                            .Emp_Pay_ID = IDx
    '                            .Emp_Pay_Method_Default_ID = dtaa.Emp_Pay_Method_Default_ID
    '                            .Emp_Pay_Detail_Std = True
    '                            .Emp_Pay_Detail_GL_Account_ID = dtaa.Emp_Pay_Salary_Default_GL_Accounts_ID
    '                            .Emp_Pay_Detail_Pay_Rate = 0
    '                        End With
    '                        db.Emp_Pay_Detail.Add(ffnew)
    '                    End If

    '                        'Dim dtabm = (From a In kmk.Emp_Pay_Detail Select a).ToList
    '                        'If dtabm.Count > 0 Then
    '                        '    'MsgBox(dtabm.Count)
    '                        '    For Each fgfg In dtabm
    '                        '        If fgfg.Emp_Pay_Method_Default_ID = dtaa.Emp_Pay_Method_Default_ID And fgfg.Emp_Pay_Method_Default.Emp_Pay_Method_ID = gg Then
    '                        '        Else
    '                        '            MsgBox(fgfg.Emp_Pay_Method_Default.Emp_Pay_Salary_Default_FieldName & " " & fgfg.Emp_Pay_Detail_ID)
    '                        '            'db.Emp_Pay_Detail.Remove(fgfg)
    '                        '        End If
    '                        '    Next
    '                        'End If

    '                Next
    '                db.SaveChanges()
    '            End If


    '            Dim dtab = (From a In kmk.Emp_Pay_Detail Where a.Emp_Pay_Method_Default.Emp_Pay_Method_ID = gg
    '                       Select New With {
    '            a.Emp_Pay_Detail_ID,
    '            .Emp_Pay_Method_Default_ID = a.Emp_Pay_Method_Default_ID,
    '            a.Emp_Pay_Detail_Std,
    '            a.Emp_Pay_Detail_GL_Account_ID,
    '            a.Emp_Pay_Detail_Pay_Rate
    '                       }).ToList
    '            If dtab.Count > 0 Then
    '                GridControl2.DataSource = dtab
    '            Else
    '                GridControl2.DataSource = Nothing
    '            End If
    '            'If dtab.Count > 0 Then


    '            ''Dim dta = (From b In db.Emp_Pay_Method_Default Where b.Emp_Pay_Method_ID = gg
    '            ''           Group Join d In db.Emp_Pay_Detail.Where(Function(o) o.Emp_Pay_ID = IDx)
    '            ''           On b.Emp_Pay_Method_Default_ID Equals d.Emp_Pay_Method_Default_ID
    '            ''Into z = Group
    '            ''From x In z.DefaultIfEmpty()
    '            ''Select New With {
    '            ''x.Emp_Pay_Detail_ID,
    '            ''.Emp_Pay_Method_Default_ID = b.Emp_Pay_Method_Default_ID,
    '            ''x.Emp_Pay_Detail_Std,
    '            ''x.Emp_Pay_Detail_GL_Account_ID,
    '            ''x.Emp_Pay_Detail_Pay_Rate
    '            ''           }).ToList


    '            'Else


    '            ''Dim ghg = (From a In db.Emp_Pay_Method_Default Where a.Emp_Pay_Method_ID = gg Select a).ToList
    '            ''If ghg.Count > 0 Then
    '            ''    For Each hgh In ghg
    '            ''        Dim ffnew = New Emp_Pay_Detail
    '            ''        With ffnew
    '            ''            .Emp_Pay_ID = IDx
    '            ''            .Emp_Pay_Method_Default_ID = hgh.Emp_Pay_Method_Default_ID
    '            ''            .Emp_Pay_Detail_Std = True
    '            ''            .Emp_Pay_Detail_GL_Account_ID = hgh.Emp_Pay_Salary_Default_GL_Accounts_ID
    '            ''            .Emp_Pay_Detail_Pay_Rate = 0
    '            ''        End With
    '            ''        db.Emp_Pay_Detail.Add(ffnew)
    '            ''    Next
    '            ''    db.SaveChanges()
    '            ''    'MsgBox("brutal save")
    '            ''End If

    '            ''Dim dtac = (From b In db.Emp_Pay_Method_Default Where b.Emp_Pay_Method_ID = gg
    '            ''           Group Join d In db.Emp_Pay_Detail.Where(Function(o) o.Emp_Pay_ID = IDx)
    '            ''           On b.Emp_Pay_Method_Default_ID Equals d.Emp_Pay_Method_Default_ID
    '            ''Into z = Group
    '            ''From x In z.DefaultIfEmpty()
    '            ''Select New With {
    '            ''x.Emp_Pay_Detail_ID,
    '            ''.Emp_Pay_Method_Default_ID = b.Emp_Pay_Method_Default_ID,
    '            ''x.Emp_Pay_Detail_Std,
    '            ''x.Emp_Pay_Detail_GL_Account_ID,
    '            ''x.Emp_Pay_Detail_Pay_Rate
    '            ''           }).ToList
    '            ''If dtac.Count > 0 Then
    '            ''    GridControl2.DataSource = dtac
    '            ''    'MsgBox("loaddd")
    '            ''Else
    '            ''    GridControl2.DataSource = Nothing
    '            ''End If


    '            'End If
    '        End If
    '            'Else
    '            'Dim dta = (From b In db.Emp_Pay_Method_Default Where b.Emp_Pay_Method_ID = 1
    '            '   Select New With {
    '            '.Emp_Pay_Detail_ID = b.Emp_Pay_Salary_Default_ID,
    '            '.Emp_Pay_Detail_Field_Name_ID = b.Emp_Pay_Salary_Default_ID,
    '            '.Emp_Pay_Detail_Std = True,
    '            '.Emp_Pay_Detail_GL_Account_ID = b.Emp_Pay_Salary_Default_GL_Accounts_ID,
    '            '.Emp_Pay_Detail_Pay_Rate = 0}).ToList
    '            'If dta.Count > 0 Then
    '            '    GridControl2.DataSource = dta
    '            'Else
    '            '    GridControl2.DataSource = Nothing
    '            'End If
    '            'End If
    '            'Catch ex As Exception
    '            '    MsgBox("Something wrong. Please contact Provider")
    '            'End Try
    '    End Using
    'End Sub
    Private Sub GridView3_CellValueChanged(sender As Object, e As DevExpress.XtraGrid.Views.Base.CellValueChangedEventArgs)
        'h {.Emp_Custom_Fields_Default_ID = a.Emp_Custom_Fields_Default_Caption, b.Emp_Custom_Fields_Default_Text}

        'Using db As New CsmdBioAttendenceEntities
        '    Dim kk As String = GridView3.GetFocusedRowCellValue("Emp_Custom_Fields_Default_ID")
        '    Dim hh As Integer = db.Emp_Custom_Fields_Default.Where(Function(o) o.Emp_Custom_Fields_Default_Caption = kk).FirstOrDefault.Emp_Custom_Fields_Default_ID
        '    Dim dt = (From a In db.Emp_Custom_Fields Where a.Emp_ID = ghj And a.Emp_Custom_Fields_Default_ID = hh Select a).FirstOrDefault
        '    If dt IsNot Nothing Then
        '        If e.Column.FieldName = "Emp_Custom_Fields_Default_Text" Then
        '            dt.Emp_Custom_Fields_Default_Text = e.Value.ToString
        '        End If
        '    Else
        '        Dim dtNew = New Emp_Custom_Fields
        '        With dtNew
        '            .Emp_ID = ghj
        '            .Emp_Custom_Fields_Default_ID = hh
        '            .Emp_Custom_Fields_Default_Text = e.Value.ToString
        '        End With
        '        db.Emp_Custom_Fields.Add(dtNew)
        '    End If
        '    db.SaveChanges()

        'End Using
    End Sub
    Private Sub GridView2_CellValueChanged(sender As Object, e As DevExpress.XtraGrid.Views.Base.CellValueChangedEventArgs)
        'Using db As New CsmdBioAttendenceEntities
        '    Dim kk As Integer = GridView2.GetFocusedRowCellValue("Emp_Pay_Detail_ID")
        '    Dim dt = (From a In db.Emp_Pay_Detail Where a.Emp_Pay_Detail_ID = kk Select a).FirstOrDefault
        '    If dt IsNot Nothing Then
        '        If e.Column.FieldName = "Emp_Pay_Detail_Std" Then
        '            dt.Emp_Pay_Detail_Std = e.Value.ToString
        '            If dt.Emp_Pay_Detail_Std = True Then

        '                Dim gh = (From a In db.Emp_Pay_Method_Default Where a.Emp_Pay_Method_Default_ID = dt.Emp_Pay_Method_Default_ID Select a).FirstOrDefault
        '                If gh IsNot Nothing Then
        '                    dt.Emp_Pay_Detail_GL_Account_ID = gh.Emp_Pay_Salary_Default_GL_Accounts_ID
        '                    GridView2.SetFocusedRowCellValue("Emp_Pay_Detail_GL_Account_ID", gh.Emp_Pay_Salary_Default_GL_Accounts_ID)
        '                End If
        '            End If
        '        End If
        '        If e.Column.FieldName = "Emp_Pay_Detail_GL_Account_ID" Then
        '            dt.Emp_Pay_Detail_GL_Account_ID = e.Value.ToString
        '        End If
        '        If e.Column.FieldName = "Emp_Pay_Detail_Pay_Rate" Then
        '            dt.Emp_Pay_Detail_Pay_Rate = If(e.Value.ToString = "", 0, e.Value.ToString)
        '        End If

        '    Else

        '    End If
        '    db.SaveChanges()
        '    Load_EMP_PayRoll_Jounal()
        'End Using
    End Sub

    'Private Sub GridView2_CustomRowCellEdit(sender As Object, e As DevExpress.XtraGrid.Views.Grid.CustomRowCellEditEventArgs)
    '    If GridView2.GetFocusedRowCellValue("Emp_Pay_Detail_Std") = True Then
    '        GridView2.Columns("Emp_Pay_Detail_GL_Account_ID").OptionsColumn.AllowEdit = False

    '    End If
    '    If GridView2.GetFocusedRowCellValue("Emp_Pay_Detail_Std") = False Then
    '        GridView2.Columns("Emp_Pay_Detail_GL_Account_ID").OptionsColumn.AllowEdit = True
    '    End If
    'End Sub

    'Dim DataT As New DataTable
    'Dim DtRow As DataRow
    'Private Sub Load_EMP_PayRoll_Jounal()
    '    Using db As New CsmdBioAttendenceEntities
    '        DataT.Rows.Clear()
    '        DataT.Columns.Clear()
    '        DataT.Columns.Add("Emp_GL_ID", GetType(Integer))
    '        DataT.Columns.Add("Emp_GL_Account_No", GetType(String))
    '        DataT.Columns.Add("Emp_GL_Description", GetType(String))
    '        DataT.Columns.Add("Emp_GL_Debit", GetType(Double))
    '        DataT.Columns.Add("Emp_GL_Credit", GetType(Decimal))

    '        Dim MethodID As Integer = Emp_Pay_Method_ID.EditValue
    '        Dim dt = (From a In db.Emp_Pay Where a.Emp_ID = ghj And a.Emp_Pay_Method_ID = MethodID Select a).FirstOrDefault
    '        If dt IsNot Nothing Then
    '            Dim dts = (From a In dt.Emp_Pay_Detail Select a).ToList
    '            If dts.Count > 0 Then
    '                Dim TotalExPEN As Double = 0
    '                For Each dtX In dts
    '                    If Not dtX.Emp_Pay_Detail_Pay_Rate = 0 Then
    '                        DtRow = DataT.NewRow
    '                        DtRow.Item("Emp_GL_Account_No") = dtX.Chart_Of_Accounts.Chart_Of_Accounts_Code
    '                        DtRow.Item("Emp_GL_Description") = dtX.Chart_Of_Accounts.Chart_Of_Accounts_Description
    '                        DtRow.Item("Emp_GL_Debit") = CType(dtX.Emp_Pay_Detail_Pay_Rate, Double)
    '                        'DtRow.Item("Emp_GL_Credit") = 0
    '                        DataT.Rows.Add(DtRow)
    '                        TotalExPEN = TotalExPEN + dtX.Emp_Pay_Detail_Pay_Rate
    '                    End If
    '                Next
    '                DtRow = DataT.NewRow
    '                DtRow.Item("Emp_GL_Account_No") = "101"
    '                DtRow.Item("Emp_GL_Description") = "Payroll Checking Account"
    '                'DtRow.Item("Emp_GL_Debit") = 0
    '                DtRow.Item("Emp_GL_Credit") = TotalExPEN
    '                DataT.Rows.Add(DtRow)
    '                GridView2.Columns("Emp_Pay_Detail_GL_Account_ID").SummaryItem.SetSummary(DevExpress.Data.SummaryItemType.Custom, "Annual Amount (" & TotalExPEN * 12 & ") pay per Month.")
    '                GridView5.Columns("Emp_GL_Debit").SummaryItem.SetSummary(DevExpress.Data.SummaryItemType.Custom, TotalExPEN)
    '                GridView5.Columns("Emp_GL_Credit").SummaryItem.SetSummary(DevExpress.Data.SummaryItemType.Custom, TotalExPEN)
    '            End If
    '            GridControl5.DataSource = DataT


    '        Else
    '            GridControl5.DataSource = Nothing
    '        End If

    '    End Using
    'End Sub


    'Private Sub LoadEditvalueChange()
    '    Using db As New CsmdBioAttendenceEntities
    '        'Try
    '        Dim gg As Integer = Emp_Pay_Method_ID.EditValue
    '        'Load_cmb_Emp_Pay_Method_Default.ColumnsAndData(RepositoryItemLookUpEdit1, gg)
    '        'Load_cmb_Chart_Of_Accounts_ID.ColumnsAndData(RepositoryItemLookUpEdit2)
    '        'MsgBox(ghj)
    '        Dim dtE = (From a In db.Emp_Pay Where a.Emp_ID = ghj Select a).FirstOrDefault
    '        If dtE IsNot Nothing Then
    '            With dtE
    '                .Emp_ID = ghj
    '                'Emp_Pay_Method_ID.EditValue = .Emp_Pay_Method_ID
    '                'Emp_Pay_Frequency_ID.EditValue = .Emp_Pay_Frequency_ID
    '                'Student_Source_Travel_ID.EditValue = .Student_Source_Travel_ID
    '                'Drv_ID.EditValue = .Drv_ID
    '                .Emp_Pay_Method_ID = Emp_Pay_Method_ID.EditValue
    '                .Emp_Pay_Frequency_ID = Emp_Pay_Frequency_ID.EditValue
    '                .Student_Source_Travel_ID = Student_Source_Travel_ID.EditValue
    '                .Drv_ID = Drv_ID.EditValue
    '                db.SaveChanges()
    '                LoadPayDetail(dtE.Emp_Pay_ID)
    '            End With

    '        Else
    '            'Emp_Pay_Method_ID.EditValue = Nothing
    '            'Emp_Pay_Frequency_ID.EditValue = Nothing
    '            'Student_Source_Travel_ID.EditValue = Nothing
    '            'Drv_ID.EditValue = Nothing
    '            If Not Emp_Pay_Method_ID.EditValue = Nothing Then
    '                Dim dtEnew = New Emp_Pay
    '                With dtEnew
    '                    .Emp_ID = ghj
    '                    .Emp_Pay_Method_ID = Emp_Pay_Method_ID.EditValue
    '                    .Emp_Pay_Frequency_ID = Emp_Pay_Frequency_ID.EditValue
    '                    .Student_Source_Travel_ID = Student_Source_Travel_ID.EditValue
    '                    .Drv_ID = Drv_ID.EditValue
    '                End With
    '                db.Emp_Pay.Add(dtEnew)
    '                db.SaveChanges()
    '            Else

    '            End If

    '            'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    '            Dim dtEhh = (From a In db.Emp_Pay Where a.Emp_ID = ghj Select a).FirstOrDefault
    '            If dtEhh IsNot Nothing Then
    '                LoadPayDetail(dtEhh.Emp_Pay_ID)
    '            Else
    '                GridControl2.DataSource = Nothing
    '            End If
    '        End If

    '        Load_EMP_PayRoll_Jounal()
    '        'Catch ex As Exception
    '        '    MsgBox("Please Select Employee ID or Left Bar")
    '        'End Try
    '    End Using
    'End Sub

    Private Sub Emp_Pay_Frequency_ID_EditValueChanged(sender As Object, e As EventArgs)
        'LoadEditvalueChange()
    End Sub

    Private Sub SearchLookUpEdit1_EditValueChanged(sender As Object, e As EventArgs) Handles SearchLookUpEdit1.EditValueChanged
        Try
            LoadTeachersRecords(SearchLookUpEdit1.EditValue)
        Catch ex As Exception

        End Try
    End Sub

    Private Sub LoadTile()
        Using db As New CsmdBioAttendenceEntities
            Dim dt = (From a In db.Employees Where a.Emp_Status = True Select a).ToList
            If dt.Count > 0 Then

                Dim grp As New TileBarGroup
                TileBar1.Groups.Clear()
                For Each dts In dt

                    'TileEle.
                    Dim item As New TileBarItem
                    Dim TileEle As New TileItemElement
                    Try
                        TileEle.Image = DbToImg(dts.Emp_Image)
                    Catch ex As Exception
                        TileEle.Image = Image.FromFile(Application.StartupPath & "\Images\Empty.jpg")
                    End Try
                    TileEle.ImageScaleMode = TileItemImageScaleMode.Stretch
                    TileEle.ImageLocation = New Point(-13, 0)
                    TileEle.ImageSize = New Size(35, 40)
                    TileEle.ImageAlignment = TileItemContentAlignment.MiddleLeft

                    item.Elements.Add(TileEle)
                    item.Elements.Add(New TileItemElement With {.Text = dts.Emp_Name, .TextAlignment = TileItemContentAlignment.TopLeft, .TextLocation = New Point(25, -6)})
                    item.Elements.Add(New TileItemElement With {.Text = dts.Emp_Father, .TextAlignment = TileItemContentAlignment.MiddleLeft, .TextLocation = New Point(25, 0)})
                    item.Elements.Add(New TileItemElement With {.Text = If(Not IsNothing(dts.Emp_Address), dts.Emp_Address, ""), .TextAlignment = TileItemContentAlignment.BottomLeft, .TextLocation = New Point(25, 6)})
                    item.Elements.Add(New TileItemElement With {.Text = dts.Emp_ID, .TextAlignment = TileItemContentAlignment.TopLeft, .TextLocation = New Point(-50, 0)})

                    item.ItemSize = TileItemSize.Wide
                    item.ShowItemShadow = DevExpress.Utils.DefaultBoolean.True
                    grp.Items.Add(item)

                Next
                'TileBar1.ShowItemShadow = True
                TileBar1.Groups.Add(grp)
            End If
        End Using
    End Sub

    Private Sub TileBar1_Click(sender As Object, e As EventArgs) Handles TileBar1.Click

    End Sub

    Private Sub TileBar1_ItemClick(sender As Object, e As TileItemEventArgs) Handles TileBar1.ItemClick

        'LoadTeachersRecords(e.Item.Elements(4).Text)
        SearchLookUpEdit1.EditValue = e.Item.Elements(4).Text
    End Sub

    'Private Sub GridView2_KeyDown(sender As Object, e As KeyEventArgs)
    '    If e.KeyCode = Keys.F5 Or e.KeyCode = Keys.R Then
    '        LoadTeachersRecords(SearchLookUpEdit1.EditValue)
    '    End If
    '    If e.KeyCode = Keys.Enter Then
    '        GridView2.MoveNext()
    '    End If
    'End Sub
    'Private Sub GridView3_KeyDown(sender As Object, e As KeyEventArgs)
    '    If e.KeyCode = Keys.F5 Or e.KeyCode = Keys.R Then
    '        LoadTeachersRecords(SearchLookUpEdit1.EditValue)
    '    End If
    '    If e.KeyCode = Keys.Enter Then
    '        GridView3.MoveNext()
    '    End If
    'End Sub

    Private Sub CheckEdit1_CheckedChanged(sender As Object, e As EventArgs)

    End Sub

    Private Sub Emp_Address_ID_ButtonClick(sender As Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs)
        'Select Case e.Button.Index
        '    Case 1
        '        frmAddress.ShowDialog()
        '    Case 2
        '        LoadAddress.ColumnsAndData(Emp_Address_ID)
        'End Select
    End Sub
End Class