'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Plaza_User
    Public Property User_ID As Integer
    Public Property User_Type_ID As Nullable(Of Integer)
    Public Property User_Name As String
    Public Property User_Pass As String
    Public Property User_Status As Nullable(Of Boolean)

    Public Overridable Property User_Type As User_Type
    Public Overridable Property Employees As ICollection(Of Employee) = New HashSet(Of Employee)

End Class
