'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User_Type
    Public Property User_Type_ID As Integer
    Public Property User_Type1 As String

    Public Overridable Property Plaza_User As ICollection(Of Plaza_User) = New HashSet(Of Plaza_User)

End Class
